### PR TITLE
TST: munge time broken

### LINKED ISSUE #237: _munge_time broken
https://travis-ci.org/xpdAcq/xpdAn/jobs/263914210#L1159

It seems that datetime is no longer imported.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #237 
Or at least adds a test which breaks.
@arkilic

### CODE REVIEW

**Comment by danielballan** [comment]
A PR that "Closes #237" would have added the missing import.

In this case, however, the right fix is just to delete `_munge_time`, which was moved to `databroker.eventsources.archiver` (along with that vanished `datetime` import) but never deleted here.

Given that `_munge_time` isn't even used internally, I'm very curious how you discovered this.

**Comment by danielballan** [comment]
Closing in favor of #242. Sorry to discard this work, CJ. You'd have to have read our minds to know what the right fix was here. :- D

**Comment by CJ-Wright** [comment]
Its fine, this PR was (as a few others were) designed to highlight an error. I find that PRs with breaking tests are the best way to provide a bug report since they are run against a neutral system (and PRs usually grab your attention :smiling_imp:) and give an example of expected behavior. I kinda wish that _munge_time was more accessible since we use it in some xpdAn/xpdAcq code to produce more human readable date/times. Is there a more accessible function for that?

**Comment by CJ-Wright** [comment]
As to your question of how I found it; I'm me.
I most likely saw when it in to the code base originally. It is used in my implementation of [`beamtime_dates`](https://github.com/xpdAcq/xpdAn/blob/master/xpdan/fuzzybroker.py#L131) as a short cut way to make nice human readable dates.

**Comment by danielballan** [comment]
> I kinda wish that _munge_time was more accessible since we use it in some xpdAn/xpdAcq code to produce more human readable date/times. Is there a more accessible function for that?

It's a two-liner; I suggest vendoring it in xpdAcq directly.

**Comment by CJ-Wright** [comment]
Fair enough

**Pull request closed without merging**
