### PR TITLE
Missing dask

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by tacaswell** [comment]
restarted the 3.5 failure, the 2.7 failure is pims/six related.

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by tacaswell** [comment]
attn @licode The recipe will also need to be updated

**Comment by licode** [comment]
Sure, I will add dask there.

**Comment by danielballan** [comment]
@CJ-Wright Can you insert it in such a way that it maintains the alphabetic sorting? This makes it easy to check whether a dependency is included.

**Comment by tacaswell** [comment]
taken care of in #312 Thanks @CJ-Wright !

**Pull request closed without merging**
