### PR TITLE
Change HDF5 Handlers to return dask objects opposed to pims

### PR DESCRIPTION
**Pull request by stuwilkins**
Note : This is WIP to try, do not merge

### CODE REVIEW

**Comment by danielballan** [comment]
:+1:

**Comment by danielballan** [comment]
This branch picked up a ton of commits that are in master. Can you rebase or cherry-pick?

**Comment by stuwilkins** [comment]
@danielballan 
I am going to blow this away.

**Comment by stuwilkins** [comment]
@danielballan I will make a much cleaner version now I know what we have to do.

**Comment by danielballan** [comment]
Cool.

**Pull request closed without merging**
