### PR TITLE
PRF: make sqlite find lazy

### LINKED ISSUE #342: `header.documents(fill=True)` is caching data?
My understanding of the documents being held in the generator was to prevent the data from taking over all the memory. However, when I load up 54 images via a for loop it seems that my memory piles up, to the tune of 7GB just looping through the documents. Is this operating properly?
```python
db_path = '/media/christopher/DATA/Research/Columbia/pal/db'
config = {'description': 'lightweight personal database',
          'metadatastore': {'module': 'databroker.headersource.sqlite',
                            'class': 'MDS',
                            'config': {'directory': db_path,
                                       'timezone': 'US/Eastern'}},
          'assets': {'module': 'databroker.assets.sqlite',
                     'class': 'Registry',
                     'config': {'dbpath': db_path + '/database.sql'}}}
for n, d in db[-1].documents(fill=True):
    # source.emit((n, d))
    if n == 'event':
        print(d['data']['image])
```
I think (I used real data to produce this) this databroker can be created by
```python
from databroker.broker import Broker
import uuid
import numpy as np
import os
from bluesky.utils import new_uid
import time

class NpyWriter:
    """
    Each call to the ``write`` method saves a file and creates a new filestore
    resource and datum record.
    """

    SPEC = 'npy'

    def __init__(self, fs, root):
        self._root = root
        self._closed = False
        self._fs = fs
        # Open and stash a file handle (e.g., h5py.File) if applicable.

    def write(self, data):
        """
        Save data to file, generate and insert new resource and datum.
        """
        if self._closed:
            raise RuntimeError('This writer has been closed.')
        fp = '{}.npy'.format(str(uuid.uuid4()))
        np.save(os.path.join(self._root, fp), data)
        resource = self._fs.insert_resource(self.SPEC, fp, resource_kwargs={},
                                            root=self._root)
        datum_id = str(uuid.uuid4())
        self._fs.insert_datum(resource=resource, datum_id=datum_id,
                              datum_kwargs={})
        return datum_id

    def close(self):
        self._closed = True

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


db_path = '/media/christopher/DATA/Research/Columbia/pal/db'
config = {'description': 'lightweight personal database',
          'metadatastore': {'module': 'databroker.headersource.sqlite',
                            'class': 'MDS',
                            'config': {'directory': db_path,
                                       'timezone': 'US/Eastern'}},
          'assets': {'module': 'databroker.assets.sqlite',
                     'class': 'Registry',
                     'config': {'dbpath': db_path + '/database.sql'}}}

db = Broker.from_config(config)
writer = NpyWriter(db.fs, db_path)

def run():
    start = {}
    descriptor = {}
    for i in range(55):
        if not start:
            suid = new_uid()
            start = {'uid': suid, 'time': time.time()}
            yield 'start', start
        if not descriptor:
            duid = new_uid()
            descriptor = {'uid': duid,
                          'name': 'primary',
                          'run_start': suid,
                          'data_keys': {
                              'image': {
                                  'source': 'sidewinder', 'dtype': 'array',
                                  'shape': [2880, 2880], 'unit': 'NA'}},
                          'time': time.time()}
            yield 'descriptor', descriptor
        yield 'event', {'uid': new_uid(),
                         'descriptor': duid,
                         'filled': {'image': True},
                         'data': {'image': np.random.random((2880, 2880))},
                         'timestamps': {'image': time.time(),},
                         'seq_num': i,
                         'time': time.time(),
                         }
    yield 'stop', {'uid': new_uid(), 'run_start': suid,
                   'time': time.time()}

for n, d in run():
    if n == 'descriptor':
        d['data_keys']['image']['external'] = True
    if n == 'event':
        d['data']['image'] = writer.write(d['data']['image'])
        d['filled']['image'] = False
    db.insert(n, d)
```

### PR DESCRIPTION
**Pull request by tacaswell**
closes #342

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
looks good to me. amazing!

**Comment by CJ-Wright** [comment]
How did the coverage get so good with only 3 lines different?

**Comment by licode** [comment]
Save lot of memory, and this should be faster. LGTM

**Comment by CJ-Wright** [comment]
It seems that all the checks have passed, and reviews are good, can this go in?

**Pull request merged**
