### PR TITLE
Api asset rewrite

### PR DESCRIPTION
**Pull request by tacaswell**
~~Not ready to merge yet.~~~

Ready to review

### CODE REVIEW

**Comment by danielballan** [comment]
(Note: one the 3.x builds passed, and the other failed randomly on socket-related stuff.)

**Comment by tacaswell** [comment]
github seems to be sorting the commits based on time, not on their actual order....

**Comment by danielballan** [comment]
I found that yesterday too.

**Comment by danielballan** [comment]
Thought I was losing my mind.

**Comment by tacaswell** [comment]
https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/ <- for the record it has apparently always been this way

**Pull request merged**
