### PR TITLE
API: change arg name from name -> stream_name

### PR DESCRIPTION
**Pull request by tacaswell**
Change the name of the 5th positional arg in `get_table` from `name` ->
'stream_name`.  The new argname is clearer and aligns with the naming
convention used in LiveTable.

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @licode You should follow this naming convention in suitcase as well.

**Comment by klauer** [comment]
Breaks backward-compatibility and will cause confusion 👎

**Comment by tacaswell** [comment]
as far as I know no one know how to use this yet.  The point of this change is to reduce confusion with naming conventions.

**Comment by licode** [comment]
Sure, I didn't start the other PR to suitcase yet. I will do it today following the name convention.

**Comment by danielballan** [comment]
Yeah, AFAIK no one knows that this kwarg exists. Change now -- avoid pain later.

**Comment by klauer** [comment]
Fine, I suppose I'm in the minority then. I'll update all the places HXN uses it.

**Comment by tacaswell** [comment]
We can add it back as kwarg at the end and have it warn for a bit.

**Pull request merged**
