### PR TITLE
Export size

### LINKED ISSUE #108: ENH: check total filesize for db.export()
When exporting it might be nice to check/print the total size of the files to be exported, otherwise we might run out of disk space. This way we can let the users know that they need to clear some space or figure something else out to complete the export.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #108

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@danielballan @tacaswell ready for review.

**Comment by danielballan** [comment]
Seems useful. Maybe wait to merge until #107 lands and that decide what the right API is. Such as `headers.__sizeof__`.

**Comment by CJ-Wright** [comment]
Ok

**Comment by danielballan** [comment]
I think this is worth putting in basically as is. Can you rebase?

**Pull request merged**
