### PR TITLE
DO NOT MERGE YET Initial effort to make metadataservice to work with databroker

### PR DESCRIPTION
**Pull request by arkilic**
Event Descriptor schema expected seems different:
https://gist.github.com/arkilic/e12272eb3099d75f3708

### CODE REVIEW

**Comment by tacaswell** [comment]
I could have sworn I fixed up all of the examples...

**Comment by arkilic** [comment]
If any consolation, the issue originates from examples that are then used in tests: https://github.com/NSLS-II/databroker/blob/master/databroker/examples/sample_data/step_scan.py#L23-L27

**Comment by arkilic** [comment]
@danielballan Travis integration up next
```
.........
Name                                                  Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------
databroker/databroker.py                                207     58    72%   1-50, 77, 102-107, 133-135, 142-146, 153, 226, 232, 239-242, 255, 266-270, 303, 327-328, 333, 343, 351, 355, 396, 400, 413-414
databroker/examples.py                                    0      0   100%
databroker/examples/hdf_io.py                            53      0   100%
databroker/examples/sample_data.py                        1      0   100%
databroker/examples/sample_data/common_nonscalar.py      10      0   100%
databroker/examples/sample_data/frame_generators.py      24      3    88%   51, 56, 59
databroker/examples/sample_data/image_and_scalar.py      66      9    86%   31, 41-45, 128-131
databroker/examples/sample_data/step_scan.py             26      1    96%   16
databroker/handler_registration.py                       12      6    50%   1-10
databroker/pims_readers.py                               22     10    55%   4-8, 28-29, 53, 57, 61, 64
databroker/pivot.py                                      91     12    87%   5-6, 44, 46, 63, 67, 131, 140, 149, 152, 162, 165
databroker/utils.py                                       0      0   100%
databroker/utils/diagnostics.py                          23      2    91%   29-30
-----------------------------------------------------------------------------------
TOTAL                                                   535    101    81%
----------------------------------------------------------------------
Ran 40 tests in 52.958s

OK
```

**Comment by danielballan** [comment]
@tacaswell Your fixes to the examples stand. It just looks like mdc is more picky about data keys than mds: it requires a shape. I'm not sure I think that it should. Assuming scalar feels OK to me.

**Comment by arkilic** [comment]
Agreed, it is annoying having to type shape for scalar data. @danielballan mongoengine was filling shape up with ```[]``` bc of the ```ListField``` (https://github.com/NSLS-II/metadatastore/blob/master/metadatastore/odm_templates.py#L101). 

Service uses the same jsonschema validation method as bluesky where shape is required.(https://github.com/NSLS-II/bluesky/blob/master/bluesky/schema/event_descriptor.json#L1-L41). Then bs should also assume scalar? Fixing this is as simple as deleting a line for me.

**Comment by danielballan** [comment]
I see. OK, let's *require* a `shape` field to be present and list-like. Being permissive seems to create more complexity than "convenience." Users are not writing data keys out interactively.

**Comment by arkilic** [comment]
@tacaswell Will you add fixes to your tests in your PR that deals with switching between metadataservice and mds library? If so, I will close this PR

**Comment by tacaswell** [comment]
Can move the logic from mdc tests to here as well so it will stat up the mdservice server on travis?

**Comment by arkilic** [comment]
Yes, we can

**Comment by tacaswell** [comment]
I am getting on failure locally:

```
======================================================================
FAIL: databroker.tests.test_broker.test_scan_id_lookup
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/dd35/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/source/bnl/databroker/databroker/tests/test_broker.py", line 154, in test_scan_id_lookup
    assert_equal(rd2[2], header['start']['uid'])
AssertionError: '17f55e95-dfdd-4fcf-b39f-213f13333823' != '5a9d56e2-ba18-4840-8cdd-af64b08570ae'
- 17f55e95-dfdd-4fcf-b39f-213f13333823
+ 5a9d56e2-ba18-4840-8cdd-af64b08570ae

```

**Comment by arkilic** [comment]
This was fixed. Are you sure you have the correct versions of metadataservice and metadataclient running?

**Comment by tacaswell** [comment]
MDC: 8c718ae 
MDS: 28f4d80

**Comment by tacaswell** [comment]
Does https://github.com/NSLS-II/metadataservice/pull/2 need to be merged?

**Comment by arkilic** [comment]
Yes, it includes fixes to the indexing. I have seen and taken care of this test ~2+ weeks ago, if I recall correctly, it is an issue due to indexing with pymongo.ASCENDING rather than pymongo.DESCENDING which https://github.com/arkilic/metadataservice/commit/a055e607387f438457a1e6b466aeddba3b1657c3 addresses

**Comment by danielballan** [comment]
Superceded by #41; closing with @arkilic's blessing.

**Comment by arkilic** [comment]
:+1:

**Pull request closed without merging**
