### PR TITLE
TST: test double access of table

### PR DESCRIPTION
**Pull request by CJ-Wright**
Ran across an issue where the databroker returns empty tables if you ask it for the same table twice. I am trying to test it.
Note that this is using a mongoquery backend although I think this may be a problem with `AD_TIFF`.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@danielballan @tacaswell @arkilic Thoughts?
I tried using JSON after the sqlite issues.

**Comment by CJ-Wright** [comment]
@chiahaoliu if you can, please take a look at this.

**Comment by CJ-Wright** [comment]
@justcalamari

**Comment by danielballan** [comment]
Fixed by #323 (we think!) -- please reopen if this is actually another issue.

**Pull request closed without merging**
