### PR TITLE
WIP: Improving test coverage, wheee

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by tacaswell** [comment]
Don't we need `databroker/utils/console.py` for the colored text in `summarize`?

**Comment by danielballan** [comment]
I thought I remembered that but @ericdill says it's nowhere in the repo or other repos.

**Comment by tacaswell** [comment]
It was deleted here: https://github.com/NSLS-II/dataportal/pull/206/files#diff-a99b236f5625bb5a279fbd68f5993fccL399 with the verbal promise it would come back someday.

**Comment by danielballan** [comment]
Ah, indeed. Now that promise is a written one. :- ) I think it might belong in a different repo anyway.

**Pull request merged**
