### PR TITLE
ENH: Fixed typo.

### PR DESCRIPTION
**Pull request by elParcero**
Specify was spelled as specifiy.

### CODE REVIEW

**Comment by jorgediazjr** [comment]
My pleasure, @mrakitin !

**Comment by awalter-bnl** [comment]
thanks @elParcero

**Comment by jorgediazjr** [comment]
My pleasure @awalter-bnl !

**Comment by jrmlhermitte** [comment]
congrats on your first contribution to an nsls-ii package @elParcero !

**Comment by jorgediazjr** [comment]
Thank you @jrmlhermitte !

**Pull request merged**
