### PR TITLE
ENH: API to get all the resource uids for a header

### PR DESCRIPTION
**Pull request by tacaswell**
This still needs tests + relies on an un-tagged version of filestore.

### CODE REVIEW

**Comment by ericdill** [comment]
What's holding up the filestore tag?

**Comment by tacaswell** [comment]
Nothing, just that we have not created it.

**Comment by tacaswell** [comment]
Any idea what is wrong with travis now?

**Comment by ericdill** [comment]
Travis isn't loading on my phone. I'll check when I get back home

**Comment by ericdill** [comment]
is the filestore bit that this uses at least merged into master?

**Comment by tacaswell** [comment]
Yes, it's on master.

**Comment by ericdill** [comment]
Great. LGTM

**Pull request merged**
