### PR TITLE
ENH: first pass at creating glue Data objects from Headers

### PR DESCRIPTION
**Pull request by tacaswell**
I expect there to be more commits before this should be merged and we should discuss if this should be in the repository or in a stand-alone.

### CODE REVIEW

**Comment by tacaswell** [comment]
```python
from ophyd.sim import hw
from bluesky import RunEngine
import bluesky.plans as bp
from databroker import temp_config, Broker

# grab simulated hardware (inplace)
hw = hw()
db = Broker.from_config(temp_config())
RE = RunEngine()
RE.subscribe(db.insert)
```

```python
from glue import qglue
d = read_header(db[-1])
gg = qglue(d=d[0])
```

**Comment by mrakitin** [comment]
I would add:
```py
from databroker.glue import read_header
```

**Comment by mrakitin** [comment]
My snippet to get the GUI:
```python
import matplotlib.pyplot as plt
from ophyd.sim import SynAxis, SynGauss
from bluesky import RunEngine
import bluesky.plans as bp
from databroker import temp_config, Broker
from databroker.glue import read_header

db = Broker.from_config(temp_config())
RE = RunEngine()
RE.subscribe(db.insert)

motor = SynAxis(name='motor')
det = SynGauss('det', motor, 'motor', center=0, Imax=1,
               noise='uniform', sigma=1, noise_multiplier=0.1)

RE(bp.scan([det], motor, -5, 5, 10))

db[-1].table().plot('motor', 'det')
plt.show()

from glue import qglue
d = read_header(db[-1])
gg = qglue(d=d[0])
```

**Comment by mrakitin** [comment]
@tacaswell, do you want me to create PR to tacaswell:enh_create_glue_structures or another PR directly to NSLS-II:master?

**Comment by mrakitin** [comment]
Superseded by #318.

**Pull request closed without merging**
