### PR TITLE
MNT/API: raise if field does not exist

### PR DESCRIPTION
**Pull request by tacaswell**
If a given field does not exist in at least one destriptor for every
header, raise.

### CODE REVIEW

**Comment by danielballan** [comment]
Hmm. I disagree that this is desired behavior. Better to catch it downstream (or not) as in https://github.com/NSLS-II/databroker/pull/23/files

**Comment by danielballan** [comment]
Example of why this does more harm than good: if I poll during partial data collection, now I have to catch this error.

**Comment by tacaswell** [comment]
Can change it to a KeyError, but the semantics seem wrong.  In #23 you still have to catch an exception, here it is just descriptive and prompt.

**Comment by danielballan** [comment]
In #23 an empty result set becomes an error because PIMS doesn't know how to handle a sequence of length 0. (This is because it inspects the first element to glean shape, dtype.) Other downstream consumers might not have this limitation. In general, an empty collection is often a valid input.

If you are unmoved by that argument, I'll concede this one.

**Comment by danielballan** [comment]
In an offline conversation, I am basically convinced that this PR is the lesser evil.

**Pull request merged**
