### PR TITLE
Octo

### PR DESCRIPTION
**Pull request by tacaswell**
This is a work in progress to merge databroker, metadatastore, metadataclient, filestore, portable_mds, and portable_fs into a single repository.  The plan is to put all of the code in one repository because

  - when we change API / add features all must get it in lockstep so versions should stay in sync
 - there is a lot of shared code between the various backends, this makes it easier to share code
 - simplify the number of things that need to be installed.

The zoo of dependancies will be handled at install time and with judicious top-level imports.

This will go in several phase

 - [x] merge all of the histories
 - [x] re-arrange so it installs 
 - [x] re-arrange into eventsource / header source
 - [ ] remove redundent code

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Let me know when this PR starts fighting Mothra :popcorn:

**Comment by CJ-Wright** [comment]
Also can we change codecov to run on the tests?

**Comment by tacaswell** [comment]
@CJ-Wright I cherry-picked the commit

**Comment by CJ-Wright** [comment]
cool thanks @tacaswell

**Comment by klauer** [comment]
How did I miss this PR since March? 

Also, 👍 x88!

**Comment by hhslepicka** [comment]
One PR to rule them all!

**Comment by CJ-Wright** [comment]
And in the brilliant light source bind them?

**Comment by tacaswell** [comment]
We are currently failing on the 'time is hard and "Tomorrow" is ambiguous' test.  There is 4 hours a day where today is tomorrow so the time-based retrieval tests fail

**Comment by tacaswell** [comment]
- [ ] finish removing `_mds` and `_fs` packages
 - [ ] sort out why headersource.shim is not tested

**Comment by danielballan** [comment]
As previously discussed but possibly not ever written down on GitHub:

Given that this PR is potentially disruptive, any new release this cycle will branch off of the 0.8.x release series.

We intend to continue moving code and removing redundant code and tests until the packages `_mds/` and `_fs/` are empty and can be removed entirely. We also intend to maximize code reuse between metadatastore and the variants that formerly comprised portable_mds, a job that is partly but not entirely done and, obviously, requires care.

With that, LEROYYYY JENKINSSSS etc....

**Comment by klauer** [comment]
👏

**Comment by CJ-Wright** [comment]
WOOOO!

**Comment by hhslepicka** [comment]
🎉  :feelsgood: 👏

**Comment by licode** [comment]
:1st_place_medal:

**Comment by stuartcampbell** [comment]
🍻 👏

**Pull request merged**
