### PR TITLE
Fix timezones

### PR DESCRIPTION
**Pull request by tacaswell**
```python
import databroker
import bluesky
import bluesky.plans as bp
import datetime
from bluesky.examples import det

# or a port
# import metadatastore.mds
# mds = metadatastore.mds.MDS({'host': 'localhost', 'database': 'time_test', 'port': 27017,
#                              'timezone': 'US/Eastern'}, auth=False)

import portable_mds.sqlite.mds as pmsm

mds = pmsm.MDS({'directory': '/tmp/pmds', 'timezone': 'US/Eastern'})
db = databroker.Broker(mds, None)



class TimeFaker:
    def __init__(self, mds, start_time, step):
        self.start_time = start_time.timestamp()
        self.step = step
        self.counter = 0
        self.mds = mds
        self.last_uid = None
        
    def insert(self, name, doc):
        if name == 'start':
            self.counter = 0
            self.last_uid = doc['uid']
            
        if 'time' in doc:
            doc['time'] = self.start_time + self.counter * self.step
        self.counter += 1
        self.mds.insert(name, doc)
    

start_time = datetime.datetime(2016, 3, 12, 23, 5)
# start_time = datetime.datetime(2016, 11, 5, 23, 5)

tf = TimeFaker(db.mds, start_time, 5*60)

RE = bluesky.RunEngine()
RE.subscribe('all', tf.insert)

RE(bp.count([det], 50))

print(db.get_table(db[tf.last_uid]))
```

which gives the following tables
<details>
```
In [20]:                   time  det
1  2016-11-05 23:15:00  1.0
2  2016-11-05 23:20:00  1.0
3  2016-11-05 23:25:00  1.0
4  2016-11-05 23:30:00  1.0
5  2016-11-05 23:35:00  1.0
6  2016-11-05 23:40:00  1.0
7  2016-11-05 23:45:00  1.0
8  2016-11-05 23:50:00  1.0
9  2016-11-05 23:55:00  1.0
10 2016-11-06 00:00:00  1.0
11 2016-11-06 00:05:00  1.0
12 2016-11-06 00:10:00  1.0
13 2016-11-06 00:15:00  1.0
14 2016-11-06 00:20:00  1.0
15 2016-11-06 00:25:00  1.0
16 2016-11-06 00:30:00  1.0
17 2016-11-06 00:35:00  1.0
18 2016-11-06 00:40:00  1.0
19 2016-11-06 00:45:00  1.0
20 2016-11-06 00:50:00  1.0
21 2016-11-06 00:55:00  1.0
22 2016-11-06 01:00:00  1.0
23 2016-11-06 01:05:00  1.0
24 2016-11-06 01:10:00  1.0
25 2016-11-06 01:15:00  1.0
26 2016-11-06 01:20:00  1.0
27 2016-11-06 01:25:00  1.0
28 2016-11-06 01:30:00  1.0
29 2016-11-06 01:35:00  1.0
30 2016-11-06 01:40:00  1.0
31 2016-11-06 01:45:00  1.0
32 2016-11-06 01:50:00  1.0
33 2016-11-06 01:55:00  1.0
34 2016-11-06 01:00:00  1.0
35 2016-11-06 01:05:00  1.0
36 2016-11-06 01:10:00  1.0
37 2016-11-06 01:15:00  1.0
38 2016-11-06 01:20:00  1.0
39 2016-11-06 01:25:00  1.0
40 2016-11-06 01:30:00  1.0
41 2016-11-06 01:35:00  1.0
42 2016-11-06 01:40:00  1.0
43 2016-11-06 01:45:00  1.0
44 2016-11-06 01:50:00  1.0
45 2016-11-06 01:55:00  1.0
46 2016-11-06 02:00:00  1.0
47 2016-11-06 02:05:00  1.0
48 2016-11-06 02:10:00  1.0
49 2016-11-06 02:15:00  1.0
50 2016-11-06 02:20:00  1.0

In [21]:                   time  det
1  2016-03-12 23:15:00  1.0
2  2016-03-12 23:20:00  1.0
3  2016-03-12 23:25:00  1.0
4  2016-03-12 23:30:00  1.0
5  2016-03-12 23:35:00  1.0
6  2016-03-12 23:40:00  1.0
7  2016-03-12 23:45:00  1.0
8  2016-03-12 23:50:00  1.0
9  2016-03-12 23:55:00  1.0
10 2016-03-13 00:00:00  1.0
11 2016-03-13 00:05:00  1.0
12 2016-03-13 00:10:00  1.0
13 2016-03-13 00:15:00  1.0
14 2016-03-13 00:20:00  1.0
15 2016-03-13 00:25:00  1.0
16 2016-03-13 00:30:00  1.0
17 2016-03-13 00:35:00  1.0
18 2016-03-13 00:40:00  1.0
19 2016-03-13 00:45:00  1.0
20 2016-03-13 00:50:00  1.0
21 2016-03-13 00:55:00  1.0
22 2016-03-13 01:00:00  1.0
23 2016-03-13 01:05:00  1.0
24 2016-03-13 01:10:00  1.0
25 2016-03-13 01:15:00  1.0
26 2016-03-13 01:20:00  1.0
27 2016-03-13 01:25:00  1.0
28 2016-03-13 01:30:00  1.0
29 2016-03-13 01:35:00  1.0
30 2016-03-13 01:40:00  1.0
31 2016-03-13 01:45:00  1.0
32 2016-03-13 01:50:00  1.0
33 2016-03-13 01:55:00  1.0
34 2016-03-13 03:00:00  1.0
35 2016-03-13 03:05:00  1.0
36 2016-03-13 03:10:00  1.0
37 2016-03-13 03:15:00  1.0
38 2016-03-13 03:20:00  1.0
39 2016-03-13 03:25:00  1.0
40 2016-03-13 03:30:00  1.0
41 2016-03-13 03:35:00  1.0
42 2016-03-13 03:40:00  1.0
43 2016-03-13 03:45:00  1.0
44 2016-03-13 03:50:00  1.0
45 2016-03-13 03:55:00  1.0
46 2016-03-13 04:00:00  1.0
47 2016-03-13 04:05:00  1.0
48 2016-03-13 04:10:00  1.0
49 2016-03-13 04:15:00  1.0
50 2016-03-13 04:20:00  1.0

In [22]: 
```
</details>

This should probably pick up a test or two.  Fortunately the failure mode here is only on spring forward so this will not break this weekend.

The data was always being saved correctly as UTC, this is purely a data extraction issue (so no risk of future data loss and no existing data is corrupted).

The underlying bug is mirrored to https://github.com/NSLS-II/datamuxer/issues/3 and needs a PR into muxer to fix.

### CODE REVIEW

**Comment by tacaswell** [comment]
a source of our confusion was https://github.com/pandas-dev/pandas/issues/6415 which causes the `utc` kwarg to sometimes be ignored which lead to us being confused about when the result was tz-aware/naive which lead to the improper localization.

**Comment by CJ-Wright** [comment]
What happens if we use the databroker to handle data from other timezones? Will the data be displayed in the timezone that it was taken in?

**Comment by tacaswell** [comment]
The time zone that it is localized to in the timezone in the mds configuration (which really should move up to the broker level, but).  If you are using the 'localized' flag then all of the tables that come out of that databroker/mds complex will have the same timezone.

All data should be recorded as UTC timestamps (as that is what is easily and directly comparable).

We should probably add an extra flag to return tz-aware datetime64 objects.

**Comment by tacaswell** [comment]
This was not really ready to be merged yet

**Comment by arkilic** [comment]
See https://github.com/NSLS-II/databroker/pull/97 in case you want to revert

**Comment by tacaswell** [comment]
I'll just open a new PR

**Comment by arkilic** [comment]
👍

**Pull request merged**
