### PR TITLE
WIP: do not use singletons from mds/fs

### PR DESCRIPTION
**Pull request by tacaswell**
this breaks all the tests

attn @danielballan

### CODE REVIEW

**Comment by arkilic** [comment]
@tacaswell this breaks EVERYTHING

**Comment by klauer** [comment]
@arkilic @tacaswell Does this break everything?

**Comment by danielballan** [comment]
Sounds like a great opportunity for me to rename everything.

**Comment by tacaswell** [comment]
We should only use the letters `{'n', 'd','b', 'l', 'a', }` in the names of things.

**Comment by danielballan** [comment]
Superceded.

**Pull request closed without merging**
